
export const AVATARS = [
    '/images/avatars/avatar_01.png',
    '/images/avatars/avatar_02.png',
    '/images/avatars/avatar_03.png',
    '/images/avatars/avatar_04.png',
    '/images/avatars/avatar_05.png',
    '/images/avatars/avatar_06.png',
    '/images/avatars/avatar_07.png',
    '/images/avatars/avatar_08.png',
    '/images/avatars/avatar_09.png',
    '/images/avatars/avatar_10.png',
    '/images/avatars/avatar_11.png',
    '/images/avatars/avatar_12.png',
    '/images/avatars/avatar_13.png',
    '/images/avatars/avatar_14.png',
    '/images/avatars/avatar_15.png',
    '/images/avatars/avatar_16.png',
    '/images/avatars/avatar_17.png',
    '/images/avatars/avatar_18.png',
    '/images/avatars/avatar_19.png',
    '/images/avatars/avatar_20.png',
    '/images/avatars/avatar_21.png',
    '/images/avatars/avatar_22.png',
    '/images/avatars/avatar_23.png',
    '/images/avatars/avatar_24.png',
    '/images/avatars/avatar_25.png',
];
