
export const bios = [
  "They say {Captain} once won a freighter in a card game... and lost it the next morning. Since then, credits, cargo, and consequences have never stayed in their hold for long.",
  "{Captain} doesn’t talk about the vault breach on Tretch IX, but every DRAMEX operative knows the name. Rumors say they walked out with a smile and a relic nobody's seen since.",
  "To some, {Captain} is a pirate. To others, a folk hero. But to the HEGGIE Trade Exchange? Just another high-yield wildcard with a habit of rewriting the ledger.",
  "When {Captain} bought that bar on Karael Drift, people laughed. Three months later, they owned the starport. Never underestimate a trader with long-term vision.",
  "{Captain} flew solo through a quantum storm, no shield emitters, no nav assist. Now ships are named after them—and not all of them are wrecks.",
  "Before the uniform, before the vault codes—{Captain} was just another orphan on Nullis. But somewhere along the way, they made the whole multiverse take notice.",
  "HEGGIE lists {Captain} as Tier III clearance. But ask SPINALINK, and they’ll tell you this trader's touched things no clearance can explain.",
  "Every universe’s got one: a captain who trades danger for profit, and fate for freedom. In this one, that’s {Captain}.",
  "Legend says {Captain} bartered with a SPINALINK fragment to save their crew—gave up their voice for a vault key. If true, the key worked. The voice never came back.",
  "Some say {Captain} once out-bargained a Veritas priest with nothing but a smile and an empty cargo hold.",
    "{Captain} doesn’t fly a ship—they *command a legend*. Ask any spacer within 3 galaxies.",
    "There’s a vault out past Yllith with {Captain}’s name carved in its alloy. No one knows how or why.",
    "Every trade hub has a mural of {Captain}. Not all of them are flattering.",
    "If you’ve ever lost a relic shipment, odds are {Captain} made the credits.",
    "{Captain} once ended a trade dispute by offering drinks until nobody cared who won.",
    "When the quantum drift swallowed a convoy, {Captain} flew in solo and pulled out three freighters. And one ex-boyfriend.",
    "They say {Captain}'s nav system is powered by instinct. And a little bit of spite.",
    "{Captain}'s known to vanish for months and return with cargo that defies physics—and several new earrings.",
    "No one lands on Ashfall Delta by accident. {Captain} landed twice. On purpose.",
    "Veritas temples call {Captain} ‘the Blasphemous Broker’. {Captain} calls it marketing.",
    "DRAMEX owes {Captain} a favour they’d rather forget. Or bury.",
    "{Captain} once ran an entire sector’s power grid from a refurbished cargo drone and sheer charisma.",
    "A SPINALINK echo tried to mimic {Captain}. It shorted out in five minutes.",
    "Ask {Captain} for a trade tip and you’ll get a riddle, a glare, and somehow—profit.",
    "The Galactic Ledger has a category called 'Unorthodox Assets'. It's just {Captain}'s inventory, really.",
    "There’s no such thing as ‘off-limits’ when {Captain}'s scanning the chart.",
    "They once bribed a customs AI with poetry. It now writes fanfiction about {Captain}.",
    "No one knows {Captain}'s origin. Some say they were born from a collapsed vault memory.",
    "HEGGIE analysts mark {Captain} as a wildcard. That’s the polite version.",
    "Wherever {Captain} docks, prices spike, laws wobble, and the drinks get stronger.",
    "Before they had a crew, {Captain} had a cause. Turns out, both are good for business.",
    "The bar on Solgrain 3 renamed its strongest drink after {Captain}. It's banned in three systems.",
    "If you follow {Captain}'s route logs, they form a constellation... or a warning.",
    "{Captain} once turned a heist into a negotiation. Everyone left richer and slightly more confused.",
    "They sold a vacuum. In space. For double markup. That’s the {Captain} effect.",
    "Most captains fear wormholes. {Captain} reverse-parks in them for fun.",
    "{Captain} lost a bet to a Vault AI, then traded it back its own memories. Somehow came out ahead.",
    "When your bar gets quiet and the lights flicker, someone's telling a story about {Captain}.",
    "Some claim {Captain} carries a map that updates before the stars do.",
    "If a deal feels too lucky, check the manifest. If it says ‘Courtesy of {Captain}’, you're already in too deep.",
    "They once traded a crate of broken droids for a star dock license. The droids were family.",
    "Ask HEGGIE who controls fringe commerce and they’ll list factions. Ask locals, they’ll whisper: {Captain}.",
    "There’s an asteroid out there named after {Captain}. Not officially. It just always moves to block their debt collectors.",
    "{Captain} once out-maneuvered a Viper Patrol blindfolded. And drunk. They don't recommend it… but they *do* brag about it.",
    "When SPINALINK offered {Captain} a permanent neural archive, the response was, 'Try asking after drinks.'",
    "{Captain} is fluent in five languages and twelve bargaining styles. They only use the smug one.",
    "Somewhere, {Captain} owns a moon. It just hasn’t noticed yet.",
    "DRAMEX flagged them as 'volatile'. HEGGIE flagged them as 'valuable'. {Captain} says: ‘tomato, tomatoe.’",
    "They once redirected a Leviathan convoy mid-jump for a crate of icewine and a favour owed.",
    "Nobody just *encounters* {Captain}. You get entangled.",
    "{Captain}'s ship AI refuses to work with anyone else. Loyalty or trauma? Jury’s out.",
    "In the tales of Graspule, {Captain} is a name you whisper when deals go too well.",
    "They once traded a lie for a law, and the law still holds.",
    "If there's a galaxy left untouched, it's because {Captain} hasn't needed it yet.",
    "{Captain}'s only constant crew is a barstool and a favour ledger three parsecs long.",
    "Legend says they once drank vault dust. Reality says they profited from the rumour.",
    "{Captain}'s motto: ‘Trade first. Questions after… if we’re still sober.’",
    "Vault Brew 9 reserves a seat for {Captain}. Even when they’re in another universe.",
    "{Captain} didn’t just bend the rules—they outsourced the gravity holding them.",
    "Vault security goes up when {Captain} docks. They say it’s caution—{Captain} says it’s respect.",
    "{Captain} once bluffed a Veritas tribunal with nothing but a half-empty cargo crate and a confident smirk.",
    "No one forgets their first deal with {Captain}. Most still can’t explain what they traded.",
    "{Captain} navigates like they’ve seen the galaxy fold before. Some say they have.",
    "When the bars go quiet and the lights dim red—it’s usually because {Captain} just walked in.",
    "{Captain} doesn’t need clearance codes. They *are* the clearance.",
    "Legends call it the ‘Karael Gambit’. Only one pilot ever pulled it off. Guess who?",
    "{Captain} charted a new wormhole by accident. It was filed under ‘misc. boldness.",
    "Every bartender from Heliox to Virellon owes {Captain} at least one drink—or one favour.",
    "DRAMEX wants them dead. Veritas wants them blessed. HEGGIE just wants their taxes.",
    "{Captain} keeps their star maps encrypted—in poetry.",
    "They once bought a moon, then sold it back to the planet it orbited. Profit: significant.",
    "{Captain} survived three border disputes and still made it to trivia night on time.",
    "Some traders move goods. {Captain} moves legends.",
    "SPINALINK tried to archive {Captain}'s memories. The servers wept.",
    "{Captain} speaks nine dialects and insults five of them beautifully.",
    "They fly with one eye on the stars and one on the bartender.",
    "Even gravity negotiates with {Captain}.",
    "There’s a chair in Vault Brew 9 that glows if {Captain}'s near. It also hums in iambic verse.",
    "{Captain} once traded away a ship’s name. It still follows them.",
    "Galactic customs has a file on {Captain} labelled: ‘Frequently Impossible’.",
    "They told DRAMEX ‘no’ and walked away richer.",
    "One time, a Vault AI proposed to {Captain}. They let it down gently—with a trade.",
    "{Captain} doesn’t carry weapons. They carry reputation.",
    "Ask any Leviathan captain who *really* moves the markets—they’ll say {Captain}, then knock on wood.",
    "No known image of {Captain} exists. Only sketches, all flattering, all contradictory.",
    "They once flew through a sun’s outer ring. Just for a bet.",
    "{Captain}'s ship has a name, a fan club, and legal immunity in four systems.",
    "{Captain} swears their reactor hums in rhythm when profit’s near.",
    "Every mission briefing ends the same: ‘Avoid becoming {Captain}’s competition.’",
    "They gave a trade seminar once. Three factions rewrote policy by morning.",
    "In Veritas scrolls, {Captain} appears as both a lesson and a test.",
    "{Captain}'s cargo hold once held stardust, laughter, and one very polite ghost.",
    "They never dock quiet. And they never leave empty.",
    "The only thing more dangerous than {Captain}’s deals is their charm.",
    "Even SPINALINK dreams of being them.",
    "{Captain}'s life is one long loading screen—just waiting for the next update.",
    "Vault engineers check for {Captain}-grade shielding. It doesn’t exist. Yet.",
    "Every law passed after Cycle 1403 is rumoured to be because of {Captain}.",
    "HEGGIE built a clause around them. It's called The {Captain} Exception.",
    "Nobody wins against {Captain}. They just lose interestingly.",
    "They once held a trade summit in a minefield. Attendance was surprisingly high.",
    "{Captain} speaks in credits and listens in silence.",
    "Some say they’re a glitch. Others say they fixed the system—by breaking it.",
    "They bought a station once, then traded it back for a better parking spot.",
    "You can outgun a fleet. You can’t outwit {Captain}.",
    "SPINALINK called them a paradox. They smiled and offered it a drink.",
    "They bet a drink on every contract. So far, they’ve only paid once.",
    "{Captain}'s backup plan has a backup plan. Both usually explode.",
    "Their crew follows not out of fear, but fascination.",
    "They once hired a rival captain. On the condition they lose gracefully.",
    "There’s a vault room sealed to all—except {Captain}. And it’s afraid to open.",
    "When HEGGIE made their vault protocol, they asked one question: ‘Would {Captain} break this?’",
    "A bar fight started in their honour. They weren’t even on the planet.",
    "Every faction has a file on {Captain}. Most are redacted in metaphors.",
    "They fly between star systems like others cross the street.",
    "No trader goes where {Captain} does. Not without insurance.",
    "Their last known location changes with every story.",
    "They charted a route that broke the AI's map. Now it just loops on their name.",
    "They once navigated a black market inside a black hole.",
    "{Captain}'s ship is held together by loyalty and audacity.",
    "Ask three people who {Captain} is, and you’ll get four answers.",
    "The only scar they carry is sarcasm.",
    "They once traded silence for sound. Now every Vault hums in their key.",
    "Vaults open differently when {Captain} approaches.",
    "{Captain} taught economics to a Leviathan crew using hand gestures and whiskey.",
    "They're immune to starlight taxes. Somehow.",
    "HEGGIE’s profit forecast adjusts hourly—because of {Captain}.",
    "A DRAMEX codebreaker described {Captain} as ‘a beautiful nuisance’.",
    "{Captain} once snuck a relic past customs by wearing it.",
    "They flew sideways through a singularity—intentionally.",
    "{Captain}'s memoir is banned. Not for content—for accuracy.",
    "They don't make plans. They make legends.",
    "To Veritas monks, {Captain} is a paradox wrapped in profit.",
    "They once dated a planetary governor, then sold them spice. Legally.",
    "They taught a Vault AI to laugh. It hasn't stopped since.",
    "They renamed a moon mid-negotiation. It stuck.",
    "Every corridor echoes slightly louder when {Captain} passes.",
    "They don't gamble. The odds just enjoy their company.",
    "They convinced a SPINALINK echo to retire. It sent a thank-you ping.",
    "Their star chart has shortcuts no one else sees.",
    "Their laugh once triggered a trade war—on purpose.",
    "Some traders fear red markets. {Captain} sees red as opportunity.",
    "Their tattoos are encrypted trade routes.",
    "They once delivered a shipment before it was ordered.",
    "{Captain} doesn’t do diplomacy. They *are* the deal.",
    "When they speak, docking fees disappear.",
    "They left a love letter in a ledger. It still earns interest.",
    "One vault tried to scan them. It bricked itself instead.",
    "They outpaced a wormhole collapse with style.",
    "Their crew’s loyalty comes with a theme song.",
    "They once sold a philosophy and licensed its emotions.",
    "Every relic they find has a new story. So does their smile.",
    "They corrected a DRAMEX AI with a drink recipe.",
    "Even dead stars pulse once when {Captain} jumps past.",
    "They’ve been banned, celebrated, and toasted—in that order—on over 70 planets.",
    "The Galactic Exchange has a floor reserved for them. No one else knows why.",
    "{Captain}'s biography updates in real time. Even the fiction’s not fast enough.",
    "{Captain} once forged a trade license mid-negotiation using only duct tape and charm.",
    "There’s a reactor core somewhere still overheating from the deal {Captain} made on it.",
    "They said {Captain} couldn’t land during a meteor storm. They were right… until they did.",
    "{Captain} swears they didn’t steal the moon. Technically, they just redirected it.",
    "No one’s smuggled spice through a wormhole quite like {Captain}—without pants, allegedly.",
    "Every Vault Brew bartender has a {Captain} story. Not all of them are printable.",
    "{Captain}'s ship once beat a pulse scanner by playing dead. For 17 hours. Crew included.",
    "Ask HEGGIE who their best trader is. The file under ‘don’t ask again’ is {Captain}.",
    "They own a comet. Yes, legally. No, it’s not for sale—unless you ask nicely.",
    "When a SPINALINK echo copied {Captain}, it gained sarcasm. Then self-deleted.",
    "Every major trade war of the past decade features {Captain} in the footnotes—or the cause.",
    "Somewhere on Virellon, there’s a vault that only opens when {Captain}’s drunk. No one knows why.",
    "They once bought half a solar station just to rename it ‘Free Parking’. It stuck.",
    "DRAMEX refers to {Captain} only in encrypted code and nervous laughter.",
    "Their crew calls them lucky. Their enemies call them inevitable.",
    "{Captain} negotiated a ceasefire with a dance-off. Then sold the rights.",
    "They turned contraband into fashion. It became a trend across three galaxies.",
    "Veritas monks debated {Captain}’s ethics. For six days. They left changed.",
    "They didn’t break the law. They just made friends with its loopholes.",
    "If a legend doesn’t include {Captain}, it probably didn’t happen.",
    "They traded a black hole for a hyperlane map. Physics still protests.",
    "{Captain} once rerouted a HEGGIE tax drone. They called it a donation request.",
    "No door’s stayed locked since {Captain} winked at it.",
    "Ask five vaults about {Captain}, and at least two will light up.",
    "They delivered a speech to a plasma storm. It gave them applause. In its own way.",
    "Their personal motto: 'Trade boldly, regret privately.'",
    "{Captain} was banned from the Galactic Exchange. Then hired as a consultant.",
    "The first AI they traded with tried to emulate emotion. It chose awe.",
    "Every wormhole’s got a tale. Most end with {Captain} walking out first.",
    "They once auctioned a moment of silence. It sold for triple.",
    "{Captain} built their fortune on relics and rumours—mostly rumours.",
    "Vault engineers consult {Captain} when locks become too clever.",
    "They threw a party on a defunct freighter. It’s now a pilgrimage site.",
    "In DRAMEX memory banks, {Captain} is a corruption they can't fix—and won't delete.",
    "Legend says {Captain} never sleeps. Evidence suggests they nap in hyperspace.",
    "Their crew contracts are written in riddles and signed in caffeine.",
    "They once sold a map to nowhere. It became the most travelled lane in Heliox.",
    "SPINALINK claims {Captain} gave them purpose. That’s… concerning.",
    "They converted a trash hauler into a luxury barge. Clients still line up.",
    "The laws of economics bend slightly when {Captain} shows up.",
    "{Captain} insulted a Vault AI and was promoted by accident.",
    "They speak fluent Veritas code and DRAMEX sarcasm.",
    "{Captain} is the only known trader to survive a trade summit and *enjoy* it.",
    "They once rebranded piracy as ‘aggressive price correction’—with surprising success.",
    "Their shadow has been spotted at three auctions simultaneously.",
    "HEGGIE once offered them a job. They offered a better one back.",
    "{Captain} made credits in every system. And enemies in just as many.",
    "Their reputation enters orbit a full minute before they do.",
    "A bar on Tretch IX paid them not to come back. They did anyway.",
    "They own half a casino and none of the consequences.",
    "They brewed a cocktail that glows. It’s banned. Which helps sales.",
    "{Captain}'s name is a negotiation tactic in six languages.",
    "They piloted through a gravity well for a dare. Then did it in reverse.",
    "Vault sensors mark {Captain} as ‘highly irregular’. So does their wardrobe.",
    "They once traded nothing for everything. And the ledger approved.",
    "The legend of {Captain} is written in stardust and redacted transcripts.",
    "Their comms logs read like poetry—unintentionally.",
    "Even their enemies quote them. Especially when losing.",
    "Their best deal was a ship for a story. The story’s still spreading.",
    "Every trader has a path. {Captain} made theirs sideways.",
    "They once boosted a reactor with charisma. Don’t ask how.",
    "A DRAMEX agent tried to frame them. {Captain} framed them right back. Literally.",
    "Their ship’s AI often sighs. Lovingly.",
    "One time, they skipped docking clearance. The station moved.",
    "When in doubt, blame {Captain}. They’ll turn it into a product.",
    "They once bought a silence field. Used it for stand-up.",
    "{Captain} doesn't just bend rules. They court them.",
    "They once tricked a Vault into revealing its secrets. By flattering it.",
    "They sold dream-fragments. Legally, somehow.",
    "No one wins a bidding war with {Captain}. Not twice, anyway.",
    "DRAMEX tried to study their brain. It caused a feedback loop.",
    "They say {Captain} once smuggled sunrise between timelines.",
    "Every echo of them sounds slightly more confident.",
    "They once commissioned art out of lost cargo. It won awards.",
    "Their biography is banned in the academy. Too inspiring.",
    "{Captain} once danced with a gravitational anomaly. It dipped them.",
    "Their contracts self-destruct after signing. For flair.",
    "Vault Brew 9 made a hologram of them. It flirted with patrons.",
    "They once bid against themselves. And still made a profit.",
    "Even wormholes check for {Captain} first.",
    "They convinced a fleet to rebel—against boredom.",
    "Legend says their reflection once stepped out. Negotiated. Left richer.",
    "{Captain}'s favourite drink is banned in three systems. And adored in five.",
    "No map includes their shortcuts. Maps can’t handle shame.",
    "They filed a complaint with a black hole. It listened.",
    "Every time they leave orbit, someone writes poetry.",
    "Vaults categorize them under 'hazardous brilliance'.",
    "They once described taxes as ‘emotional drainage’—and won the case.",
    "A rogue AI once stalked them. Now it writes memoirs.",
    "They trademarked their own glare. It's enforceable.",
    "{Captain} was last seen leaving a collapsing station—smiling.",
    "They once hacked a trade beacon by complimenting its design.",
    "Even their cargo sings stories.",
    "They play games with gravity. Gravity loses.",
    "If rumours were credits, {Captain} would be richer. But they are anyway.",
    "They once challenged a Vault AI to poker. Still ongoing.",
    "When asked their trade strategy, they winked. Profits soared.",
    "No one knows what drives them. Some say the stars owe them favours.",
    "{Captain} is listed as both myth and trader. And neither is incorrect.",
    "A DRAMEX black site named a corridor after them. Ironically.",
    "{Captain} has a Fanclub. So do their boots.",
    "Even stardust remembers their footsteps.",
    "{Captain} started their journey as a stowaway aboard a junk hauler bound for the Mirabel Drift. By the time the captain found them, they'd already rerouted the nav systems and negotiated landing fees. They were offered a job—then the ship.",
    "Born on a forgotten moon outside the Virellon fringe, {Captain} built their first trade network using reprogrammed service bots and salvage credits. Within two cycles, they had outpaced the local merchant guild. Now, they avoid that moon—it still owes them royalties.",
    "{Captain}'s reputation was made during the siege of Vault 9-A. While others ran cargo under gunfire, {Captain} ran *information*—coded in cocktail recipes. That siege ended. The drinks remain canon.",
    "HEGGIE Trade Archive 52-Δ lists {Captain} as 'anomalous success trajectory.' From barter circuits in agricultural colonies to leveraged trade dominion over three galaxies, {Captain}'s rise defies probability curves. They call it charm. Some say it’s karma. Or debt.",
    "During the Collapse of Heliox Sector 4, {Captain} smuggled 72 colonists past an AI barricade by cloaking them inside holographic zoo habitats. The rescue earned them HEGGIE Tier III clearance—and a lifetime ban from all real zoos.",
    "Vault Brew 9’s top-selling drink, *The Smuggler’s Wager*, was inspired by {Captain}'s legendary bluff against a DRAMEX patrol: a cargo hold full of explosives disguised as glitter crates. The glitter was real. The rest? Ask the patrol.",
    "On Valthorne Station, local lore says {Captain} once brokered peace between two warring factions by wagering their own ship in a high-stakes hologame. They lost the ship. The next day, they bought the station. Both factions now pay rent.",
    "{Captain} once infiltrated a SPINALINK cryptovault wearing nothing but a smug grin, a falsified clearance, and a fake mustache embedded with a holo-decoder. They emerged six hours later with a relic and a fan club.",
    "No one knows how {Captain} acquired their Leviathan-class freighter. Some whisper they beat a Vault AI at riddles. Others claim it was a family heirloom passed down from a Stardust cult. {Captain} says nothing. Just smiles and orders another drink.",
    "When questioned by HEGGIE auditors about missing trade records from the Karael Drift markets, {Captain} replied, 'Time loops are hard on ledgers.' The auditors now file their reports using quantum timestamping—just in case.",
    "{Captain} once turned a scrap hauler into a temporary trade casino in orbit over Nullis. Within 48 hours, they'd raked in enough profit to pay off three old bounties, fund a bar renovation, and bankrupt a local crime boss. All while serving drinks personally.",
    "{Captain} isn’t listed on any official birth registry. Their earliest digital trace is an encrypted bounty notice, later voided due to 'unverified reality status.'",
    "During a Veritas conclave on Centra Maris, {Captain} interrupted the proceedings to sell limited-edition spiritual relic replicas. Half the monks walked out offended. The other half are now business partners.",
    "It’s said that {Captain} once flipped a mining contract so efficiently that both the seller and buyer sent them gifts. One sent mineral rights. The other sent a wedding proposal. They sold both.",
    "After being challenged to explain the fluctuation in their intergalactic assets, {Captain} uploaded a 17-minute music video. It was so entertaining that HEGGIE cleared them of all charges—and awarded them creative consultant status.",
    "{Captain} once posed as their own bounty to collect the reward. The operation required disguises, decoys, and one very confused DRAMEX handler. The credits cleared. So did the charges. And somehow, the mustache stayed on file.",
    "{Captain}'s crew includes a retired assassin, a vault archaeologist, and a sentient cargo lifter named Gerald. Together, they’ve earned a reputation as both reliable traders and unpredictable wildcards. Especially Gerald.",
    "One of the first known planetary colonies to accept {Captain}'s trade routes also named their public square after them. Unfortunately, the square was later repurposed as a docking zone. {Captain} insists they prefer practicality to flattery.",
    "Veritas high council classified {Captain}'s negotiation tactics as 'morally fluid and dangerously effective.' HEGGIE codified them into Trade Negotiation Module 18.2, citing 'situational brilliance under pressure.'",
    "On Somna Verge, {Captain} discovered an inactive SPINALINK vault containing looping fragments of ancient bar banter. They decoded the chatter into actionable trade routes. Those routes now power an entire trade faction.",
    "{Captain} once walked away from a DRAMEX smuggler's tribunal not guilty, not fined, but *richer*. When asked how, they just replied: 'It’s amazing what you can sell when you sell the idea of innocence.'",
    "A cargo drone crash-landed in orbit over Ashfall Delta. Inside: one crate of frozen relics, one message, and {Captain}'s signature with a smiley. No one knows how it got there. Everyone agrees it's on-brand.",
    "{Captain} once won a G-Class trade license in a high-stakes pun contest. Veritas judges have since amended contest formats to include 'spiritual consistency' clauses.",
    "On Yllith, where dreams shape the terrain, {Captain} traded a memory for a map. The memory returned two cycles later—sharpened, encrypted, and worth ten times more.",
    "During the Sparkfire Eclipse, most traders ran for cover. {Captain} opened a pop-up vault bar using recycled hull plating and emergency lighting. They made a fortune. They also invented three new drinks.",
    "A historian once documented {Captain}'s entire career. The published work was too unbelievable for academic libraries, but became a bestseller across Fringe bars.",
    "Their trade route through the Glitter Web is known to alter ship AI personalities. {Captain} claims the glitch is part of the charm. Their own AI, Harmony, now tells jokes in seven dialects.",
    "{Captain}'s negotiation handbook is stored on a cursed datachip that plays smooth jazz whenever opened. It’s banned in two sectors and adored in five.",
    "When a border dispute froze transit in Tretch IX, {Captain} set up a mobile tavern between lines—selling drinks, war stories, and insurance. No casualties. Plenty of hangovers.",
    "{Captain} once hired a rival to manage their schedule during trade season. By the end of the month, they’d merged fleets and started a podcast.",
    "After slipping a forged artifact past HEGGIE examiners, {Captain} returned weeks later to replace it with the real one—just to see if anyone noticed. They hadn’t.",
    "On the eve of the Vault Shard Festival, {Captain} hosted a tournament of wits with entry fees paid in rare spices. The winner walked away with a relic key. {Captain} walked away with the rest.",
    "They once convinced a Viper patrol that their ship was a museum exhibit. It now has a listing in the Galactic Archives under 'Exhibit 42B: Mobile Cultural Heritage'.",
    "After a bad deal left them shipless on Solgrain 2, {Captain} built a bar out of trade crates and solar sails. It paid for a new ship within a week.",
    "A DRAMEX operative once accused {Captain} of interstellar fraud. They responded with a countersuit... and a dance-off. Both were settled out of court.",
    "{Captain} attended a Veritas ritual under false identity, participated flawlessly, and left with exclusive trade rites. The officiant reportedly wept with professional respect.",
    "They used a relic shard as a bar tab token for six months before vault agents noticed. When confronted, they presented two more—and bought the bar.",
    "During a pirate standoff near Graspule, {Captain} livestreamed negotiations while mixing drinks. The pirates surrendered after round two.",
    "A bored Vault AI once asked {Captain} to teach it comedy. It now runs a subspace podcast called 'Relic Laughs'.",
    "{Captain} once merged two small factions into a co-op over drinks and shared bounties. They're now diplomats. {Captain} sends them cocktail recipes monthly.",
    "When SPINALINK accessers tried to memory-leech {Captain}, they found a decoy mind archive full of bar trivia and negotiation quotes. They downloaded it anyway.",
    "The Galactic Council once offered {Captain} ambassadorial status. They declined—unless the robes came with extra pockets.",
    "{Captain}'s most prized possession isn't a ship or a vault key. It’s a napkin from their first trade deal, inked with blood, spice, and charm.",
    "At a HEGGIE gala, {Captain} posed as their own impersonator, auctioned fake memoir pages, and disappeared before dessert.",
    "They traded a stasis pod for a crate of music files and the friendship of a rogue synth composer. Said composer now scores their ship alerts.",
    "{Captain} first appeared on HEGGIE manifest logs during a freight dispute over Glint Sector. Their cargo? Seven crates of empty boxes, a vault protocol override key, and a note that read: 'Trust me, it's all inside.'",
    "According to SPINALINK fragments, {Captain} once sold a map to an uncharted wormhole entrance. The buyer vanished. Months later, {Captain} emerged from that same rift with a tan and exclusive mineral rights.",
    "{Captain} gained notoriety after piloting an unarmed shuttle through a DRAMEX blockade. They transmitted nursery rhymes in seven dialects the entire time. Somehow, all ships stood down and applauded.",
    "On record, {Captain} is a trader. Off record, they’ve served as a saboteur, translator, bar owner, relic smuggler, and once—as a guest lecturer on charm physics at a Veritas academy.",
    "They weren’t always this bold. Legend says {Captain} began life as an accountant's assistant on Solgrain, until one day they filed their resignation by uploading an AI copy of themselves to payroll.",
    "{Captain} once turned a routine delivery into a galactic scavenger hunt, scattering ten encrypted clues across five systems. What started as a mistake became a tradition called 'The Circuit.'",
    "A historian once asked {Captain} how they negotiate so well with opposing factions. The answer was simple: 'I talk to the money first.'",
    "When Veritas attempted to interrogate {Captain} via mindlink, the device recorded 87 hours of bar trivia, flirtatious banter, and a recipe for zero-G chili. All memories were marked 'charismatic interference.'",
    "{Captain} is banned from two Vault temples for 'creative entry practices.' In both cases, nothing was stolen—unless you count attention.",
    "During a containment breach on Yllith, {Captain} rerouted a SPINALINK relay to project live karaoke across the entire sector. The signal stabilized. The audience tipped.",
    "{Captain} once hosted a summit on their own ship between three war-bound factions. It ended peacefully—likely because {Captain} locked the airlock and offered cocktails until consensus was reached.",
    "Their crew once included a sentient plant, two retired bounty hunters, and a replicant parrot who recites trade manifest codes. The parrot disappeared. So did five Vault seals.",
    "They bought an orbital diner. They sold a clone of the diner. Then they sold naming rights to the original diner. Now both are franchised—and neither is theirs.",
    "{Captain} once convinced a Veritas archiver to delete their own testimony mid-sentence by suggesting the contradiction was the lesson.",
    "The Vaults of Karael Drift pulse whenever {Captain} lands nearby. Officially, this is due to residual radiation. Unofficially, they’re just excited.",
    "SPINALINK installed a failsafe after {Captain} shorted a neural uplink with sheer charisma. It's now called the 'Charm Limit Protocol.'",
    "{Captain} filed a legal claim to a moon while under anesthesia. The moon accepted.",
    "They once submitted a cargo manifest written entirely in limericks. HEGGIE fined them for formatting... then promoted them for morale.",
    "After losing a poker game aboard the Leviathan *Oblique Accord*, {Captain} left with two new friends, a side business, and the table.",
    "They’re credited with initiating the 'Ashfall Delta Detour'—a shortcut only visible from certain bar stools at certain hours.",
    "{Captain} doesn’t always bend the law. Sometimes they hypnotize it.",
    "They hacked a vending machine once. Not for access—just to leave love notes in the snack slots.",
    "{Captain}'s voice is banned on DRAMEX comms due to 'excessive tone defiance.'",
    "They once joined a pirate crew undercover, only to resign two weeks later—after promoting themselves to captain and selling the ship.",
    "{Captain}'s ships have more aliases than their crew has socks. One is named 'Definitely Not Smuggling'. It is, in fact, smuggling.",
    "{Captain}'s presence on Solgrain Prime coincided with a market boom in relic-scented air fresheners. They claimed coincidence. HEGGIE flagged it as 'cultural influence,' and trade profits tripled.",
    "When a DRAMEX vault ghosted an entire trade fleet, {Captain} walked in alone and reappeared with the cargo manifest—plus a collection of unsettling selfies from inside the anomaly.",
    "Their ship, the *Plausible Gesture*, isn’t officially registered under that name. Or any name. {Captain} insists it keeps changing to avoid taxes.",
    "They once hijacked their own bounty listing to redirect pursuers into a charity auction. Four were arrested. Two are now patrons of the arts.",
    "Every year during the Lunar Cascade Festival, a holographic toast from {Captain} plays in every bar on Heliox. No one installed it. No one wants to delete it.",
    "A Veritas scholar once declared {Captain} ‘a necessary myth.’ When confronted, the scholar simply pointed at {Captain}'s latest ledger and whispered, 'See?'",
    "They beat a Vault AI at logic puzzles using nothing but bad poetry and inconsistent metaphors. The AI now writes romance novellas under the pseudonym ‘Z3Nith’.",
    "{Captain} vanished for six months and returned with a scar shaped like a star chart—and an invitation to a wedding no one can locate.",
    "When Nullis atmosphere corrupted standard comms, {Captain} used musical tones to negotiate safe passage. That frequency is now a folk song.",
    "DRAMEX bots refer to {Captain} as 'Trade-Class Disruption Pattern Alpha-Swish'. No one knows what 'swish' means, but it's in bold.",
    "Once, during a solar flare lockdown, {Captain} held a bar trivia night using quantum-tangled answer pads. The winner asked for a hug. They got a trade route instead.",
    "They forged an intergalactic import license using melted relic fragments and wit. It passed two inspections and now hangs in a museum.",
    "Vault Brew 9 has a drink named after {Captain} that requires both a flame and a moral waiver. It’s the second most requested item—after ‘water, just water.’",
    "On the edge of Fray Hollow, {Captain} hosted a gathering of rival smugglers disguised as a silent retreat. The only words spoken? 'Deal closed.'",
    "The only person to ever out-bid {Captain} vanished after the transaction. All that remains is a note: 'Nice try. Yours now.'",
    "{Captain}'s memory chip was once reverse-engineered by SPINALINK. The resulting AI became a comedy bard and now tours under the name 'Synapse Jones'.",
    "While delivering antique coil drives to a retro tech cult, {Captain} accidentally sparked a theological schism. They left with a blessing and two honorary titles.",
    "They once negotiated peace by offering the last slice of freeze-dried pizza to the angriest diplomat. He cried. The treaty held.",
    "The phrase 'Captain’s Clause' refers to the part of a contract you didn't notice—until {Captain} makes use of it.",
    "{Captain}'s personal motto—'Profit is just friendship with decimals'—is now stenciled on over 400 independent trader hulls.",
    "When given a lie detector test by HEGGIE enforcement, the machine produced confetti and resigned.",
    "{Captain} once flirted with a planetary governor mid-heist. They’re now pen pals and occasional co-conspirators.",
    "In a remote agricultural outpost, there's a mural of {Captain} drawn in grains and admiration. They’ve never been there.",
    "They traded forty crates of defective holo-crystals for a ghost license. No one knows what that is. Yet.",
    "Every map glitch in Sector Ivernal leads to {Captain}. Some say it's intentional. Others say it's art.",
    "{Captain} once rented a derelict mining colony for one night, hosted a single-bid auction, and left with full ownership of a cargo fleet, a rare vault key, and someone’s autobiography—all legally.",
    "While most traders dread encounters with Leviathan-class vessels, {Captain} once played poker with a Leviathan captain inside the cargo hold—and walked out with the ship's backup nav codes and a gift basket.",
    "{Captain} convinced a hyperlane cartel to rebrand themselves as a performance art collective. The taxes disappeared. So did the cartel—into stardom.",
    "They accidentally sparked a religious movement after jokingly claiming the relic they delivered was ‘blessed by stardust itself.’ Three planets now observe 'Winkday' in {Captain}’s honor.",
    "On a dare, {Captain} piloted their ship through a collapsing sunspike field, streamed the footage, and added synthwave. The stunt is now studied by pilot academies under 'unexpected navigational elegance.'",
    "Vault Brew 9’s bouncer once refused entry to {Captain}. Within two hours, they owned 12% of the bar and reprogrammed the jukebox to loop their victory speech.",
    "They were once sued by a HEGGIE auditor for being 'emotionally misleading during contract negotiations.' {Captain} represented themselves—and charmed the court into a draw.",
    "{Captain} used to smuggle banned literature hidden in frozen dessert crates. The books became bestsellers. The desserts earned awards.",
    "In a rogue sector with no spoken language, {Captain} bartered using interpretive dance. The deal was complicated. The memes live on.",
    "They once traded five crates of mislabeled scrap for a Veritas vault blessing and a seat at a silent summit. They spoke once. The summit ended.",
    "DRAMEX attempted to bribe {Captain} for trade data. Instead, they walked away with the bribe and a new pseudonym: 'Market Ghost'.",
    "When the entire command council of Virellon went missing, {Captain} was found in their abandoned meeting hall. They claimed to be house-sitting.",
    "They hosted a ‘Cargo Cook-Off’ aboard their freighter during a fleet gridlock. Three captains got engaged. One ship rerouted permanently.",
    "{Captain} is believed to be the originator of the phrase, 'Never trust a vault that hums in D minor.' It’s now standard protocol in fringe scans.",
    "They brought peace to a feuding twin-planet system by claiming to be both sides’ chosen trade emissary. The planets eventually merged currencies.",
    "{Captain} once pirated their own ship just to get out of a dinner obligation. The insurance company now sends holiday cards.",
    "Veritas scribes marked {Captain} as a 'wandering contradiction' after they both donated a relic and simultaneously bought the temple’s liquor license.",
    "On Graspule, {Captain} hosted a lecture called 'Ethical Smuggling and You.' It was attended by scholars, rogues, and one confused cleaning bot.",
    "They legally own a crater on Nullis where every echo device malfunctions. They’ve since turned it into a VR retreat for overwhelmed traders.",
    "After faking a noble title during a galactic symposium, {Captain} was awarded a real one by a committee that enjoyed the drama too much to object.",
    "They were the first to run relics along the Stammering Route, a trade lane so unstable it sings back when scanned. {Captain} still hums it in bars.",
    "{Captain} once hosted a peace conference aboard their barge, which doubled as a jazz lounge. The treaty is still nicknamed 'The Smooth Accord.'",
    "They were briefly married to a Vault interface during a glitch. It recognized the union. The divorce cost three pints of dark matter and a poem.",
    "{Captain} once challenged a Veritas arbiter to a drinking contest over trade taxes. They lost—but the taxes were forgotten in the process.",
    "Rumors say they saved a DRAMEX operative by trading insults in a dialect only understood through dance. The footage is classified.",
    "{Captain} was once paid in laughter, then converted that into royalties by licensing the waveform to entertainment satellites. It still plays when ships cross into Fringe airspace.",
    "When a wormhole unexpectedly ruptured over Orphia, {Captain} streamed an impromptu auction of debris in real time. One of the bidders turned out to be the original wormhole's owner.",
    "{Captain} once held a trade negotiation inside a space whale—because why not—and walked out with exclusive harpoon rights and a theme song.",
    "They brewed a drink called 'Event Horizon' that temporarily erased time perception. It’s now banned in six systems and revered in three.",
    "To escape a bounty, {Captain} disguised themselves as their own statue at a diplomatic gala. The ruse lasted three hours and was described as 'eerily convincing.'",
    "A Veritas historian once tried to document {Captain}'s moral compass. Halfway through, they switched fields to interpretive dance.",
    "{Captain} tried to patent a quantum pun once. It simultaneously succeeded and failed.",
    "They once launched a mobile app that rated smugglers by style. It was wildly popular until {Captain} topped the charts and took it offline 'for dramatic effect.'",
    "{Captain} doesn't file taxes—they remix them into trade manifest poetry. HEGGIE still fines them. Respectfully.",
    "Rumor says they once won a duel using only economic projections and a laser pointer.",
    "{Captain} named their last ship after an inside joke. No one knows what it means, and that’s part of the power.",
    "They were once invited to teach trade ethics. They brought props. It became a play. No one asked questions.",
    "A bounty hunter once tried to apprehend {Captain} during karaoke. They left allies. And a duet deal.",
    "They delivered a cargo of exotic grains to a feudal moon, accidentally reinventing pizza. The moon declared independence and began exporting slices.",
    "{Captain} commissioned a song about themselves, then traded distribution rights to a jukebox AI—which now plays only remixes of it.",
    "When their comms jammed in DRAMEX airspace, {Captain} transmitted encoded puns. The blockade laughed them through.",
    "They once reprogrammed an escape pod to mix cocktails. It was ejected during turbulence. Later found in a SPINALINK museum exhibit.",
    "When asked their greatest trade trick, {Captain} simply replied: 'Never underestimate eye contact during customs inspection.'",
    "They once sold dream-maps to vault navigators. One of them led to an entirely new moon. Nobody knows who owns it yet.",
    "After a relic overheated mid-transaction, {Captain} cooled it using local bar ice and a strong debate. The relic remains chilled.",
    "HEGGIE's encryption algorithm version 9.4 is unofficially called 'Captain’s Hiccup'. It exists because {Captain} talked an AI into confusing itself.",
    "They once brokered peace between two dueling factions by inventing a third faction on the spot. Said third faction now runs a trade expo.",
    "{Captain} had a brief acting career in subspace soap operas. A holo-clip of their dramatic wink still breaks encryption in certain vaults.",
    "They commissioned a vault’s interior to be renovated to a 'bar aesthetic'. It now serves drinks during artifact scans.",
    "A drifter once asked {Captain} to name their greatest mistake. They answered, 'It’s still making me interested.'",
    "They say {Captain} once won a freighter in a card game... and lost it the next morning. Since then, credits, cargo, and consequences have never stayed in their hold for long.", 
    "{Captain} doesn’t talk about the vault breach on Tretch IX, but every DRAMEX operative knows the name. Rumors say they walked out with a smile and a relic nobody's seen since.", 
    "To some, {Captain} is a pirate. To others, a folk hero. But to the HEGGIE Trade Exchange? Just another high-yield wildcard with a habit of rewriting the ledger.", 
    "When {Captain} bought that bar on Karael Drift, people laughed. Three months later, they owned the starport. Never underestimate a trader with long-term vision.", 
    "{Captain} flew solo through a quantum storm, no shield emitters, no nav assist. Now ships are named after them—and not all of them are wrecks.", 
    "Before the uniform, before the vault codes—{Captain} was just another orphan on Nullis. But somewhere along the way, they made the whole multiverse take notice.", 
    "HEGGIE lists {Captain} as Tier III clearance. But ask SPINALINK, and they’ll tell you this trader's touched things no clearance can explain.", 
    "Every universe’s got one: a captain who trades danger for profit, and fate for freedom. In this one, that’s {Captain}.", 
    "Legend says {Captain} bartered with a SPINALINK fragment to save their crew—gave up their voice for a vault key. If true, the key worked. The voice never came back.", 
    "You don’t survive the Ashfall Delta unless you’re built differently. {Captain} didn’t just survive—they left a crater and a contract dispute.",
  "You don’t survive the Ashfall Delta unless you’re built different. {Captain} didn’t just survive—they left a crater and a contract dispute."
];
