'use client';
import type { DiplomaticMission } from '@/lib/types';

// This is a list of mission templates. The final 'id' and 'status' will be generated dynamically.
export const STATIC_DIPLOMATIC_MISSIONS: Omit<DiplomaticMission, 'id' | 'status'>[] = [
    // Low Risk
    {
        title: "The Cygnus Accord Mediation",
        missionType: 'Mediation',
        description: "Mediate a minor trade tariff dispute between two emerging factions in the Cygnus sector.",
        system: "Sirius",
        stakeholders: ["The Cygnus Combine", "Starlight Developments"],
        payoutCredits: 25000,
        payoutInfluence: 5,
        riskLevel: 'Low',
        duration: 300,
    },
    {
        title: "Veridian Trade Route Survey",
        missionType: 'Investigation',
        description: "Investigate claims of unauthorized tolls being levied on a new trade route. Discretion is key.",
        system: "Kepler-186f",
        stakeholders: ["Veritas Guild", "Lakon Spaceways"],
        payoutCredits: 30000,
        payoutInfluence: 7,
        riskLevel: 'Low',
        duration: 400,
    },
    {
        title: "Proxima Cultural Exchange Treaty",
        missionType: 'Treaty',
        description: "Finalize a cultural exchange treaty to foster goodwill with the independent colonies of Proxima.",
        system: "Proxima Centauri",
        stakeholders: ["Proxima Alliance", "Core Worlds Emissary"],
        payoutCredits: 20000,
        payoutInfluence: 10,
        riskLevel: 'Low',
        duration: 350,
    },

    // Medium Risk
    {
        title: "TRAPPIST-1 Artifact Provenance",
        missionType: 'Investigation',
        description: "A precursor artifact of dubious origin has appeared on the market. Verify its provenance without alerting the seller.",
        system: "TRAPPIST-1",
        stakeholders: ["Xylos Corporation", "The Collectors Guild"],
        payoutCredits: 75000,
        payoutInfluence: 15,
        riskLevel: 'Medium',
        duration: 500,
    },
    {
        title: "Sol-Sirius Border Skirmish Mediation",
        missionType: 'Mediation',
        description: "Tensions are high after a corporate security fleet fired on a civilian vessel. Broker a ceasefire before it escalates.",
        system: "Sol",
        stakeholders: ["Aegis Interstellar Bank", "Faulcon deLacy Holdings"],
        payoutCredits: 60000,
        payoutInfluence: 20,
        riskLevel: 'Medium',
        duration: 600,
    },
    {
        title: "Non-Aggression Pact: Crimson Syndicate",
        missionType: 'Treaty',
        description: "Negotiate a non-aggression pact with the infamous Crimson Syndicate to secure safe passage through their territory.",
        system: "Proxima Centauri",
        stakeholders: ["Crimson Syndicate", "HEGGIE Trade Council"],
        payoutCredits: 100000,
        payoutInfluence: 25,
        riskLevel: 'Medium',
        duration: 450,
    },

    // High Risk
    {
        title: "Investigation of Corporate Espionage",
        missionType: 'Investigation',
        description: "A high-level corporate executive is suspected of selling secrets. Infiltrate their inner circle and find proof.",
        system: "Sirius",
        stakeholders: ["Weyland-Yutani Corp", "Orion Industrial"],
        payoutCredits: 180000,
        payoutInfluence: 40,
        riskLevel: 'High',
        duration: 700,
    },
    {
        title: "The Kepler Ceasefire Summit",
        missionType: 'Mediation',
        description: "Two rival agricultural barons are on the brink of open war over water rights. Bring them to the negotiating table.",
        system: "Kepler-186f",
        stakeholders: ["House Valerius", "The Green-Thumb Cooperative"],
        payoutCredits: 150000,
        payoutInfluence: 35,
        riskLevel: 'High',
        duration: 800,
    },
    {
        title: "The Anarchy Accords",
        missionType: 'Treaty',
        description: "Attempt to establish a basic framework of trade law in the lawless TRAPPIST-1 system. Success is unlikely, but the rewards are immense.",
        system: "TRAPPIST-1",
        stakeholders: ["The Void Reavers", "The Scrap Lords", "The Ghosts"],
        payoutCredits: 250000,
        payoutInfluence: 60,
        riskLevel: 'High',
        duration: 900,
    },

    // Critical Risk
    {
        title: "Investigation of a Rogue AI",
        missionType: 'Investigation',
        description: "A planetary defense AI has gone rogue, seizing control of its system. Determine its motives and find a weakness before it attacks.",
        system: "Sirius",
        stakeholders: ["Aegis Defense Systems", "Galactic AI Ethics Board"],
        payoutCredits: 400000,
        payoutInfluence: 100,
        riskLevel: 'Critical',
        duration: 1200,
    },
    {
        title: "Mediation of the Secession Crisis",
        missionType: 'Mediation',
        description: "The entire Proxima Centauri system threatens to secede from the Galactic Compact. Prevent a civil war at all costs.",
        system: "Sol",
        stakeholders: ["The Proxima Separatists", "The Core Worlds Senate", "HEGGIE Security Council"],
        payoutCredits: 500000,
        payoutInfluence: 150,
        riskLevel: 'Critical',
        duration: 1500,
    },
];
