import type { StaticItem } from '@/lib/types';

export const STATIC_ITEMS: StaticItem[] = [
  // Biological
  {
    category: 'Biological',
    name: 'Stellar Hemoplasma Culture',
    rarity: 'Rare',
    description: 'A liquid culture of star-adapted blood cells.',
    detail: 'Used in long-term cryo-revival protocols; illegal in unregulated sectors due to aggressive mutation risk.',
    basePrice: 3500,
    cargoSpace: 0.5,
  },
  {
    category: 'Biological',
    name: 'Gene-Spliced Kava Root',
    rarity: 'Common',
    description: 'A fast-growing, calming root vegetable enhanced for zero-G growth.',
    detail: 'A popular, non-addictive stress relief supplement for long-haul crews.',
    basePrice: 200,
    cargoSpace: 2,
  },
  {
    category: 'Biological',
    name: 'Bioluminescent Fungi',
    rarity: 'Uncommon',
    description: 'A type of fungi that provides natural, low-energy light.',
    detail: 'Used for creating ambient lighting in luxury starship cabins and biodomes.',
    basePrice: 550,
    cargoSpace: 3,
  },
  {
    category: 'Biological',
    name: 'Mycelial Network Spores',
    rarity: 'Rare',
    description: 'Spores capable of creating a subspace communication network.',
    detail: 'Highly sought after for secure, FTL communication arrays. Very delicate.',
    basePrice: 1800,
    cargoSpace: 0.5,
  },
  {
    category: 'Biological',
    name: 'Medical Nanites',
    rarity: 'Rare',
    description: 'Programmable microscopic robots for advanced medical procedures.',
    detail: 'Can repair tissue damage at a cellular level, a staple of high-end medbays.',
    basePrice: 2200,
    cargoSpace: 0.5,
  },
  // Industrial
  {
    category: 'Industrial',
    name: 'Quantum Filament Spools',
    rarity: 'Common',
    description: 'Threaded energy-binding filaments for warp coil stabilization.',
    detail: 'Essential in retrofitting old freighters for modern jump drives.',
    basePrice: 1200,
    cargoSpace: 2,
  },
  {
    category: 'Industrial',
    name: 'Decommissioned Ship Parts',
    rarity: 'Common',
    description: 'Scrap metal and components from retired starships.',
    detail: 'A cheap source of raw materials for frontier outposts and repair docks.',
    basePrice: 450,
    cargoSpace: 20,
  },
  {
    category: 'Industrial',
    name: 'Terraforming Agents',
    rarity: 'Rare',
    description: 'A cocktail of microbes and chemicals to alter planetary atmospheres.',
    detail: 'Heavily regulated but extremely profitable for planetary development corps.',
    basePrice: 4000,
    cargoSpace: 8,
  },
  {
    category: 'Industrial',
    name: 'Cryo-Gas',
    rarity: 'Common',
    description: 'Inert gas used for industrial cooling and stasis pods.',
    detail: 'High demand in systems with large populations or advanced manufacturing.',
    basePrice: 350,
    cargoSpace: 5,
  },
  {
    category: 'Industrial',
    name: 'Refined He-3 Isotope',
    rarity: 'Uncommon',
    description: 'A stable, high-efficiency fuel source for fusion reactors.',
    detail: 'Powers everything from capital ships to planetary energy grids.',
    basePrice: 800,
    cargoSpace: 4,
  },
  // Pleasure
  {
    category: 'Pleasure',
    name: 'Nebula-Scented Glow Candles',
    rarity: 'Plentiful',
    description: 'Candles infused with iridescent gas particles and aroma sequences.',
    detail: 'Favored by influencers and diplomats for ambiance protocols.',
    basePrice: 50,
    cargoSpace: 1,
  },
  {
    category: 'Pleasure',
    name: 'Luxury Spices',
    rarity: 'Uncommon',
    description: 'Exotic seasonings from across the galaxy, prized by gourmands.',
    detail: 'A simple way to add a touch of class to any meal, from ration packs to banquets.',
    basePrice: 900,
    cargoSpace: 1,
  },
  // Food
  {
    category: 'Food',
    name: 'Cryo-Spice Ration Packs',
    rarity: 'Accessible',
    description: 'Dehydrated meals with flavor-crystals harvested from nebula fog.',
    detail: 'Provides full sensory stimulation during long-haul missions.',
    basePrice: 75,
    cargoSpace: 1,
  },
  // Military
  {
    category: 'Military',
    name: 'Ion-Tuned Smart Ammunition',
    rarity: 'Ultra Rare',
    description: 'Adaptive ammunition that aligns with magnetic anomalies.',
    detail: 'Only usable with Mk. XLII exo-rifles; banned in civilian skirmishes.',
    basePrice: 8000,
    cargoSpace: 2,
  },
  {
    category: 'Military',
    name: 'Graviton Emitters',
    rarity: 'Rare',
    description: 'Devices that create localized gravity distortions.',
    detail: 'Used for ship tractor beams and planetary defense systems. Highly restricted.',
    basePrice: 7500,
    cargoSpace: 3,
  },
  // Technology
  {
    category: 'Technology',
    name: 'Zero-Point Energy Cells',
    rarity: 'Rare',
    description: 'Harnesses vacuum energy for a near-limitless power supply.',
    detail: 'Extremely volatile but incredibly powerful. The holy grail of energy tech.',
    basePrice: 5000,
    cargoSpace: 1,
  },
  {
    category: 'Technology',
    name: 'Stellar Flares (Data)',
    rarity: 'Uncommon',
    description: 'Raw data recordings of solar phenomena, used for scientific research.',
    detail: 'Valuable to research institutions and universities studying stellar evolution.',
    basePrice: 3200,
    cargoSpace: 0.1,
  },
  {
    category: 'Technology',
    name: 'Sentient AI Cores',
    rarity: 'Ultra Rare',
    description: 'Restricted AI matrices with full self-awareness.',
    detail: 'Possession is illegal in most systems. A legal and ethical minefield.',
    basePrice: 50000,
    cargoSpace: 2,
  },
  // Minerals
  {
    category: 'Minerals',
    name: 'Asteroid Minerals',
    rarity: 'Plentiful',
    description: 'Common iron, nickel, and silicates mined from asteroid fields.',
    detail: 'The basic building blocks of all space construction.',
    basePrice: 80,
    cargoSpace: 10,
  },
  {
    category: 'Minerals',
    name: 'Xenocrystal Shards',
    rarity: 'Uncommon',
    description: 'Crystalline structures with unusual energy-focusing properties.',
    detail: 'Used in advanced laser optics and high-precision cutting tools.',
    basePrice: 2500,
    cargoSpace: 1,
  },
  {
    category: 'Minerals',
    name: 'Void Opals',
    rarity: 'Ultra Rare',
    description: 'Gemstones that seem to absorb light, mined from dead planets.',
    detail: 'Prized by collectors and mystics for their unique, unsettling beauty.',
    basePrice: 10000,
    cargoSpace: 0.2,
  },
  // Illegal
  {
    category: 'Illegal',
    name: 'Illegal Cybernetics',
    rarity: 'Rare',
    description: 'Military-grade or experimental cybernetic enhancements.',
    detail: 'Banned in most civilized systems due to their potential for misuse.',
    basePrice: 6500,
    cargoSpace: 2,
  },
];
