export const STRAPLINES = [
    "Know your limits before placing your bets.",
    "It’s a game, not a grind — keep it light.",
    "Betting shouldn’t cost your peace of mind.",
    "Don’t let chasing wins lead you off track.",
    "Take breaks — your bankroll and brain will thank you.",
    "Never gamble to fix your mood.",
    "A mate’s advice beats a losing streak.",
    "Stick to your budget, not your hopes.",
    "The house doesn’t care — your friends do.",
    "If it’s not fun, it’s not worth it.",
    "Play smart — not desperate.",
    "Pause, check your balance — financial and emotional.",
    "One more spin? Try one more walk instead.",
    "Know when to fold — in cards and in life.",
    "Don’t bet more than you’d laugh losing.",
    "Winning is thrilling, but so is walking away.",
    "Set your limits before your losses do.",
    "A cool head makes better choices.",
    "Bet time should never steal family time.",
    "Real life > reel spins. Always.",
    "Don’t let your credits drift into a black hole.",
    "Fuel up with caution — not every bet launches.",
    "If the fun goes offline, so should you.",
    "Every galaxy has limits — set yours.",
    "Don’t chase wins across wormholes.",
    "Stardust isn’t currency — know what you’re spending.",
    "Even warp-speed wins can burn out.",
    "Cool heads make stellar decisions.",
    "Play responsibly — don’t crash your ship for one spin.",
    "Betting shouldn't be your mission control.",
    "Float your credits carefully — space is vast, but budgets aren’t.",
    "Avoid gravitational loss — bet what you can afford.",
    "Trade with strategy, not desperation — even in deep space.",
    "Signal distress before your orbit breaks.",
    "A supernova loss isn’t worth the thrill.",
    "No amount of winnings can buy back time on Earth.",
    "The cosmos is unpredictable — your bets don’t need to be.",
    "Don't eject reason just to fuel risk.",
    "A peaceful mind is your best co-pilot.",
    "Keep your fun in orbit — don't let it drift too far."
];
