import type { TaxiMission } from '@/lib/types';

// This is a list of mission templates. The final 'id', 'fromSystem', and 'toSystem' will be generated dynamically.
export const STATIC_TAXI_MISSIONS: Omit<TaxiMission, 'id' | 'fromSystem' | 'toSystem' | 'status' | 'assignedShipInstanceId' | 'assignedShipName'>[] = [
    // Low Risk
    {
        passengerName: 'Corpo-auditor Klex',
        description: "A by-the-book auditor needs quiet transport for a routine system check. Expects punctuality.",
        fare: 15000,
        bonus: 4000,
        riskLevel: 'Low',
        duration: 150,
        requiredFuel: 10,
        minHullPercentage: 0.75,
    },
    {
        passengerName: 'Glitched Pleasure-bot',
        description: "A malfunctioning pleasure-bot seeks a discrete ride to a repair shop. It occasionally sings off-key.",
        fare: 18000,
        bonus: 3000,
        riskLevel: 'Low',
        duration: 180,
        requiredFuel: 15,
        minHullPercentage: 0.70,
    },
    {
        passengerName: 'A group of tourists',
        description: 'A family of sightseers wants to visit the famous nebula in the next system. They ask a lot of questions.',
        fare: 22000,
        bonus: 5000,
        riskLevel: 'Low',
        duration: 240,
        requiredFuel: 20,
        minHullPercentage: 0.80,
        minComfortLevel: 2,
    },
    // Medium Risk
    {
        passengerName: 'Down-on-his-luck prospector',
        description: "An old prospector claims to have a map to a big score in the next system. He smells faintly of desperation.",
        fare: 45000,
        bonus: 10000,
        riskLevel: 'Medium',
        duration: 200,
        requiredFuel: 25,
        minHullPercentage: 0.85,
    },
    {
        passengerName: 'Holovid starlet',
        description: "A famous actress needs to get to her next shoot without attracting paparazzi. Her luggage is... extensive. Requires a comfortable ride.",
        fare: 80000,
        bonus: 20000,
        riskLevel: 'Medium',
        duration: 190,
        requiredFuel: 22,
        minHullPercentage: 0.90,
        minComfortLevel: 4,
        minPacksLevel: 2,
    },
    // High Risk
    {
        passengerName: 'Shady informant',
        description: "A nervous informant needs to get to a safehouse before their former employers find them. Expect trouble. Security is a must.",
        fare: 125000,
        bonus: 35000,
        riskLevel: 'High',
        duration: 220,
        requiredFuel: 30,
        minHullPercentage: 0.95,
        minSecurityLevel: 5,
    },
    {
        passengerName: 'Ex-syndicate enforcer',
        description: "A heavily augmented enforcer wants a no-questions-asked ride to the outer rim. Top-tier security is non-negotiable.",
        fare: 150000,
        bonus: 40000,
        riskLevel: 'High',
        duration: 300,
        requiredFuel: 40,
        minHullPercentage: 0.95,
        minSecurityLevel: 7,
    },
    // Critical Risk
    {
        passengerName: 'Renegade AI core',
        description: "A sentient AI core, housed in a reinforced briefcase, needs extraction. It claims to know the secrets of the galaxy. Maximum security and discretion required.",
        fare: 350000,
        bonus: 100000,
        riskLevel: 'Critical',
        duration: 250,
        requiredFuel: 50,
        minHullPercentage: 1.0,
        minSecurityLevel: 8,
        minPacksLevel: 6,
    },
];
