export const traderNames = [
    "Jax 'The Comet' Williams",
    "Baron Von 'Blackhole' Hess",
    "Cmdr. Alex 'Void' Ryder",
    "Seraphina 'The Ghost' Volkov",
    "Grizelda 'Gear-Head' Petrova",
    "Silas 'Silver-Tongue' Thorne",
    "Rook 'The Rook' Castell",
    "Kaelen 'The Butcher' Vance",
    "Anya 'Void-Walker' Sharma",
    "Madame Evangeline",
    "Dread Captain 'Scar' Ironheart",
    "Admiral 'Voidgazer' Kael",
    "Captain 'Mad' Mel",
    "Commander 'Hex' Stryker",
];
